/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package eva1_2_block_notas;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.io.OutputStreamWriter;
import static java.lang.System.in;
import java.nio.file.Files;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;

/**
 *
 * @author invitado
 */
public class BlockDeNotas extends javax.swing.JFrame {

    /**
     * Creates new form BlockDeNotas
     */
    public BlockDeNotas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtareaEDITAR = new javax.swing.JTextArea();
        btnABRIR = new javax.swing.JButton();
        btnGUARDAR = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtareaEDITAR.setColumns(20);
        txtareaEDITAR.setRows(5);
        jScrollPane1.setViewportView(txtareaEDITAR);

        btnABRIR.setText("Abrir");
        btnABRIR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnABRIRMouseClicked(evt);
            }
        });

        btnGUARDAR.setText("Guardar");
        btnGUARDAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGUARDARMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnABRIR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGUARDAR, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(btnABRIR, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnGUARDAR)
                .addContainerGap(367, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnABRIRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnABRIRMouseClicked
        // TODO add your handling code here:
        //Seleccionar JFileChooser, crear el objeto y seleccionar una ruta real en el sistema
        JFileChooser jfcAbrirArch = new JFileChooser("C:\\archivos");
        //Seleccionar jfcAbrirArch, show y escoger "Open Dialog"
        int resu = jfcAbrirArch.showOpenDialog(this);
        if(resu == JFileChooser.APPROVE_OPTION){
                BufferedReader br = null;
                InputStream is = null;
            try {
                System.out.println(jfcAbrirArch.getSelectedFile());
                //Necesitamos un reader para pasarselo al text area
                is = Files.newInputStream(jfcAbrirArch.getSelectedFile().toPath());
                InputStreamReader isr = new InputStreamReader(is);
                br = new BufferedReader(isr);
                txtareaEDITAR.read(br,"Abrir archivo");
            } catch (IOException ex) {
                Logger.getLogger(BlockDeNotas.class.getName()).log(Level.SEVERE, null, ex);
        }finally{
            try{
                if(br!=null){
                br.close();
                is.close();
                  }
                }catch(IOException ex){
                    ex.printStackTrace();
                }        
            
        }
    }//GEN-LAST:event_btnABRIRMouseClicked
    }
    private void btnGUARDARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGUARDARMouseClicked
        // Haremos lo mismo que con Abrir, pero con código de salida
        JFileChooser jfcAbrirArch = new JFileChooser("C:\\archivos");
        int resu = jfcAbrirArch.showSaveDialog(this);
        if(resu == JFileChooser.APPROVE_OPTION){
            BufferedWriter bw = null;
            OutputStream os = null;
            
            try{
                os = Files.newOutputStream(jfcAbrirArch.getSelectedFile().toPath());
                OutputStreamWriter ow = new OutputStreamWriter(os);
                bw = new BufferedWriter(ow);
                txtareaEDITAR.write(ow);
            }catch(IOException ex){
                ex.printStackTrace();
            }finally{
            try{
                if(bw!=null){
                bw.close();
                os.close();
                  }
                }catch(IOException ex){
                    ex.printStackTrace();
                }
                
            }
        }
        
    }//GEN-LAST:event_btnGUARDARMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BlockDeNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BlockDeNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BlockDeNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BlockDeNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BlockDeNotas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnABRIR;
    private javax.swing.JButton btnGUARDAR;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtareaEDITAR;
    // End of variables declaration//GEN-END:variables
}
